apiVersion: v1
kind: ServiceAccount
metadata:
  name: picato-sa
  namespace: picato-prod
  labels:
    app: picato
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: picato-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: picato-rb
subjects:
- kind: ServiceAccount
  name: picato-sa
roleRef:
  kind: Role
  name: picato-role
  apiGroup: rbac.authorization.k8s.io
