apiVersion: v1
kind: Secret
metadata:
  name: picato-secret
  namespace: picato-prod  
  labels:
    app: picato
type: Opaque
stringData:
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyDummyKeyHere1234567890"
  FIREBASE_CLIENT_EMAIL: "dummy@picato-dummy.iam.gserviceaccount.com"
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7\n-----END PRIVATE KEY-----\n"
