apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: picato-monitor
  namespace: picato-prod  
  labels:
    app: picato
    release: prometheus
spec:
  selector:
    matchLabels:
      app: picato
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
